version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    # Настройка для работы через VPN
    extra_hosts:
      - "api.openai.com:104.18.2.163"  # IP адрес OpenAI через VPN
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
